name: pseudom
description: A Dart package for CSS parsing and manipulation, with added support for custom pseudo selectors.
version: 1.0.0
repository: https://github.com/hubble459/pseudom

environment:
  sdk: ^3.3.1

dependencies:
  antlr4: ^4.13.1
  html: ^0.15.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
